export const ALL_ADOPTERS_REQUEST = 'ALL_ADOPTERS_REQUEST'
export const ALL_ADOPTERS_SUCCESS = 'ALL_ADOPTERS_SUCCESS'
export const ALL_ADOPTERS_FAIL = 'ALL_ADOPTERS_FAIL'

export const ADOPTER_DETAILS_REQUEST = 'ADOPTER_DETAILS_REQUEST' 
export const ADOPTER_DETAILS_SUCCESS = 'ADOPTER_DETAILS_SUCCESS'
export const ADOPTER_DETAILS_FAIL = 'ADOPTER_DETAILS_FAIL'

export const ADMIN_ADOPTERS_REQUEST = 'ADMIN_ADOPTERS_REQUEST'
export const ADMIN_ADOPTERS_SUCCESS = 'ADMIN_ADOPTERS_SUCCESS'
export const ADMIN_ADOPTERS_FAIL = 'ADMIN_ADOPTERS_FAIL'

export const NEW_ADOPTER_REQUEST = 'NEW_ADOPTER_REQUEST'
export const NEW_ADOPTER_SUCCESS = 'NEW_ADOPTER_SUCCESS'
export const NEW_ADOPTER_RESET = 'NEW_ADOPTER_RESET'
export const NEW_ADOPTER_FAIL = 'NEW_ADOPTER_FAIL'

export const NEW_ADOPTERS_REQUEST = 'NEW_ADOPTERS_REQUEST'
export const NEW_ADOPTERS_SUCCESS = 'NEW_ADOPTERS_SUCCESS'
export const NEW_ADOPTERS_RESET = 'NEW_ADOPTERS_RESET'
export const NEW_ADOPTERS_FAIL = 'NEW_ADOPTERS_FAIL'

export const NEW_ADOPT_REQUEST = 'NEW_ADOPT_REQUEST'
export const NEW_ADOPT_SUCCESS = 'NEW_ADOPT_SUCCESS'
export const NEW_ADOPT_RESET = 'NEW_ADOPT_RESET'
export const NEW_ADOPT_FAIL = 'NEW_ADOPT_FAIL'

export const NEW_ADOPTS_REQUEST = 'NEW_ADOPTS_REQUEST'
export const NEW_ADOPTS_SUCCESS = 'NEW_ADOPTS_SUCCESS'
export const NEW_ADOPTS_RESET = 'NEW_ADOPTS_RESET'
export const NEW_ADOPTS_FAIL = 'NEW_ADOPTS_FAIL'


export const DELETE_ADOPTER_REQUEST = 'DELETE_ADOPTER_REQUEST'
export const DELETE_ADOPTER_SUCCESS = 'DELETE_ADOPTER_SUCCESS'
export const DELETE_ADOPTER_RESET = 'DELETE_ADOPTER_RESET'
export const DELETE_ADOPTER_FAIL = 'DELETE_ADOPTER_FAIL'

export const UPDATE_ADOPTER_REQUEST = 'UPDATE_ADOPTER_REQUEST'
export const UPDATE_ADOPTER_SUCCESS = 'UPDATE_ADOPTER_SUCCESS'
export const UPDATE_ADOPTER_RESET = 'UPDATE_ADOPTER_RESET'
export const UPDATE_ADOPTER_FAIL = 'UPDATE_ADOPTER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'