export const ALL_ANIMALS_REQUEST = 'ALL_ANIMALS_REQUEST'
export const ALL_ANIMALS_SUCCESS = 'ALL_ANIMALS_SUCCESS'
export const ALL_ANIMALS_FAIL = 'ALL_ANIMALS_FAIL'

export const ANIMAL_DETAILS_REQUEST = 'ANIMAL_DETAILS_REQUEST' 
export const ANIMAL_DETAILS_SUCCESS = 'ANIMAL_DETAILS_SUCCESS'
export const ANIMAL_DETAILS_FAIL = 'ANIMAL_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const ADMIN_ANIMALS_REQUEST = 'ADMIN_ANIMALS_REQUEST'
export const ADMIN_ANIMALS_SUCCESS = 'ADMIN_ANIMALS_SUCCESS'
export const ADMIN_ANIMALS_FAIL = 'ADMIN_ANIMALS_FAIL'

export const NEW_ANIMAL_REQUEST = 'NEW_ANIMAL_REQUEST'
export const NEW_ANIMAL_SUCCESS = 'NEW_ANIMAL_SUCCESS'
export const NEW_ANIMAL_RESET = 'NEW_ANIMAL_RESET'
export const NEW_ANIMAL_FAIL = 'NEW_ANIMAL_FAIL'

export const DELETE_ANIMAL_REQUEST = 'DELETE_ANIMAL_REQUEST'
export const DELETE_ANIMAL_SUCCESS = 'DELETE_ANIMAL_SUCCESS'
export const DELETE_ANIMAL_RESET = 'DELETE_ANIMAL_RESET'
export const DELETE_ANIMAL_FAIL = 'DELETE_ANIMAL_FAIL'

export const UPDATE_ANIMAL_REQUEST = 'UPDATE_ANIMAL_REQUEST'
export const UPDATE_ANIMAL_SUCCESS = 'UPDATE_ANIMAL_SUCCESS'
export const UPDATE_ANIMAL_RESET = 'UPDATE_ANIMAL_RESET'
export const UPDATE_ANIMAL_FAIL = 'UPDATE_ANIMAL_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'