export const ALL_PERSONNELS_REQUEST = 'ALL_PERSONNELS_REQUEST'
export const ALL_PERSONNELS_SUCCESS = 'ALL_PERSONNELS_SUCCESS'
export const ALL_PERSONNELS_FAIL = 'ALL_PERSONNELS_FAIL'

export const PERSONNEL_DETAILS_REQUEST = 'PERSONNEL_DETAILS_REQUEST' 
export const PERSONNEL_DETAILS_SUCCESS = 'PERSONNEL_DETAILS_SUCCESS'
export const PERSONNEL_DETAILS_FAIL = 'PERSONNEL_DETAILS_FAIL'

export const PERSONNEL_ADOPTERS_REQUEST = 'ADMIN_ADOPTERS_REQUEST'
export const PERSONNEL_ADOPTERS_SUCCESS = 'ADMIN_ADOPTERS_SUCCESS'
export const PERSONNEL_ADOPTERS_FAIL = 'ADMIN_ADOPTERS_FAIL'

export const ADMIN_PERSONNELS_REQUEST = 'ADMIN_PERSONNELS_REQUEST'
export const ADMIN_PERSONNELS_SUCCESS = 'ADMIN_PERSONNELS_SUCCESS'
export const ADMIN_PERSONNELS_FAIL = 'ADMIN_PERSONNELS_FAIL'

export const NEW_PERSONNEL_REQUEST = 'NEW_PERSONNEL_REQUEST'
export const NEW_PERSONNEL_SUCCESS = 'NEW_PERSONNEL_SUCCESS'
export const NEW_PERSONNEL_RESET = 'NEW_PERSONNEL_RESET'
export const NEW_PERSONNEL_FAIL = 'NEW_PERSONNEL_FAIL'

export const NEW_PERSONNELS_REQUEST = 'NEW_PERSONNELS_REQUEST'
export const NEW_PERSONNELS_SUCCESS = 'NEW_PERSONNELS_SUCCESS'
export const NEW_PERSONNELS_RESET = 'NEW_PERSONNELS_RESET'
export const NEW_PERSONNELS_FAIL = 'NEW_PERSONNELS_FAIL'

export const DELETE_PERSONNEL_REQUEST = 'DELETE_PERSONNEL_REQUEST'
export const DELETE_PERSONNEL_SUCCESS = 'DELETE_PERSONNEL_SUCCESS'
export const DELETE_PERSONNEL_RESET = 'DELETE_PERSONNEL_RESET'
export const DELETE_PERSONNEL_FAIL = 'DELETE_PERSONNEL_FAIL'

export const UPDATE_PERSONNEL_REQUEST = 'UPDATE_PERSONNEL_REQUEST'
export const UPDATE_PERSONNEL_SUCCESS = 'UPDATE_PERSONNEL_SUCCESS'
export const UPDATE_PERSONNEL_RESET = 'UPDATE_PERSONNEL_RESET'
export const UPDATE_PERSONNEL_FAIL = 'UPDATE_PERSONNEL_FAIL'

export const DELETE_ADOPTER_REQUEST = 'DELETE_ADOPTER_REQUEST'
export const DELETE_ADOPTER_SUCCESS = 'DELETE_ADOPTER_SUCCESS'
export const DELETE_ADOPTER_RESET = 'DELETE_ADOPTER_RESET'
export const DELETE_ADOPTER_FAIL = 'DELETE_ADOPTER_FAIL'

export const UPDATE_ADOPTER_REQUEST = 'UPDATE_ADOPTER_REQUEST'
export const UPDATE_ADOPTER_SUCCESS = 'UPDATE_ADOPTER_SUCCESS'
export const UPDATE_ADOPTER_RESET = 'UPDATE_ADOPTER_RESET'
export const UPDATE_ADOPTER_FAIL = 'UPDATE_ADOPTER_FAIL'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'